services:
  db:
    image: mysql:8.0
    container_name: sectasks-db
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sectask_db
      MYSQL_USER: sectask
      MYSQL_PASSWORD: sectaskpass

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sectasks-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3000
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: sectask
      DB_PASSWORD: sectaskpass
      DB_NAME: sectask_db
      JWT_SECRET: cambia-esto-por-una-clave-larga-y-segura
      JWT_EXPIRES_IN: 24h
      RESET_TOKEN_EXPIRES_MINUTES: 10
      RECAPTCHA_SECRET_KEY: cambia-esto-si-usas-recaptcha
    ports:
      - "3000:3000"

volumes:
  mysql_data:
